import Head from "next/head";
import Cookies from "js-cookie";
import { useRouter } from "next/router";
import React, { useContext, useEffect, useState } from "react";
import { Store } from "../../utils/Store";
import Header from "../../components/Header";

export default function Payment() {
  const [selectedPaymentMethod, setSelectedPaymentMethod] = useState("");

  const { state, dispatch } = useContext(Store);
  const { cart } = state;
  const { paymentMethod } = cart;

  const router = useRouter();

  const submitHandler = (e) => {
    e.preventDefault();
    if (!selectedPaymentMethod) {
      return alert("Payment method is required");
    }
    dispatch({ type: "SAVE_PAYMENT_METHOD", payload: selectedPaymentMethod });
    Cookies.set(
      "cart",
      JSON.stringify({
        ...cart,
        paymentMethod: selectedPaymentMethod,
      })
    );
    router.push("/Placeorder");
  };
  useEffect(() => {
    setSelectedPaymentMethod(paymentMethod || "");
  }, [paymentMethod, router]);

  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/blackhole1.ico" />
      </Head>
      <div class="fixed top-0 right-0 left-0 z-[100]">
        <Header />
      </div>

      <main class="mt-32">
        <form class="mx-auto max-w-screen-md" onSubmit={submitHandler}>
          <h1 class="mb-4 text-xl">Payment Method</h1>
          {["ETH", "USDC", "DAI", "USDT", "WBTC", "WETH"].map((payment) => {
            return (
              <div key={payment} class="mb-4">
                <input
                  name="paymentMethod"
                  class="p-2 outline-none focus:ring-0"
                  id={payment}
                  type="radio"
                  checked={selectedPaymentMethod === payment}
                  onChange={() => setSelectedPaymentMethod(payment)}
                />

                <label class="p-2" htmlFor={payment}>
                  {payment}
                </label>
              </div>
            );
          })}
          <div class="mb-4 flex justify-between">
            <button
              onClick={() => router.push("/Cart")}
              type="button"
              class="default-button"
            >
              Back
            </button>
            <button class="primary-button">Next</button>
          </div>
        </form>
      </main>
    </>
  );
}
